services:
  app:
    build: .
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  db_data:
