//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "players")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub player_uuid: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_stats::Entity")]
    PlayerStats,
}

impl Related<super::player_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
