//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "player_stats")]
#[serde(rename_all = "camelCase")]
#[schema(rename_all = "camelCase", as = PlayerStat)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub player_uuid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stat_categories_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub stat_name: String,
    pub value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
