//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player_stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub player_uuid: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub category: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub value_name: String,
    pub value: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerUuid",
        to = "super::players::Column::PlayerUuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Players,
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
